apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailsangja
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default

  source:
    repoURL: git@github.com:asitisdev/mailsangja-orbstack.git
    targetRevision: main
    path: apps/mailsangja

  destination:
    server: https://kubernetes.default.svc
    namespace: mailsangja

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/status

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
